name: Specflow Trx to Html Report
description: |
  Parse specflow dotnet trx files and generate html report with gherkin steps and attachments
author: 'Maksymilian Bahr <maks.bahr@gmail.com>'
branding:
  icon: file-text
  color: green

inputs:
  trxDirPath:
    description:
      Specifies the directory path where your test result files (.trx files) are located. Test result files are
      generated typically by dotnet testing frameworks.
    required: false
    default: '.'

  attachmentsDirPath:
    description:
      Indicates the directory path where any attachments related to the test results are stored. Attachments might
      include screenshots, log files, or any other supplementary materials.
    required: false
    default: 'undefined'

  outputHtmlPath:
    description:
      Specifies the file path for the HTML file that will be generated as a result of processing the test results.
    required: false
    default: 'output/result.html'

  reportTitle:
    description: Specifies the name of the report title and main heading.
    required: false
    default: 'Automation Test Report'

  onlySummary:
    description: Specifies whether to generate only execution and domain summary, excluding results of single tests.
    required: false
    default: 'false'

  noLogs:
    description:
      Specifies whether to display tests with logs. If set to true, logs will not be included in the HTML report and the
      log display toggle will be disabled. This reduces file size.
    required: false
    default: 'false'

  projectLogoSrc:
    description: Specifies the URL of the image to be shown in the top right corner of the report.
    required: false
    default: 'undefined'

  outputHtmlEmailPath:
    description: Specifies the file path for the HTML file that will be generated for sending as email html body
    required: false
    default: 'undefined'

  branchName:
    description: Specifies the branch name to display
    required: false
    default: 'undefined'

runs:
  using: node20
  main: dist/index.js
