name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action1
        uses: ./
        with:
          trxDirPath: './__tests__/trx'
          attachmentsDirPath: './__tests__/attachments'
          outputHtmlPath: 'output/${{ github.run_number }}-summary-test-results.html'
          projectLogoSrc: https://fontslogo.com/wp-content/uploads/2013/03/GitHub-Logo-Font.jpg
          onlySummary: true
          outputHtmlEmailPath: ${{ github.run_number }}-email-summary-ui-test-report.html

      - name: Test Local Action
        id: test-action2
        uses: ./
        with:
          trxDirPath: './__tests__/trx'
          attachmentsDirPath: './__tests__/attachments'
          outputHtmlPath: 'output/${{ github.run_number }}-full-test-results.html'
          projectLogoSrc: https://fontslogo.com/wp-content/uploads/2013/03/GitHub-Logo-Font.jpg

      - name: Save HTML summary report
        uses: actions/upload-artifact@v3
        with:
          name: HTML_Report
          path: output/${{ github.run_number }}-summary-test-results.html'

      - name: Save HTML full report
        uses: actions/upload-artifact@v3
        with:
          name: HTML_Report
          path: output/${{ github.run_number }}-full-test-results.html

      - name: Send email
        uses: dawidd6/action-send-mail@v3.11.0
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: automat.marlin.api@gmail.com
          password: ${{secrets.PASSWORD}}
          subject: ${{ github.run_number }} - Run Automation Tests
          to: mba@spyro-soft.com
          cc: automat.sbs@gmail.com
          from: Api Marlin <automat.marlin.api@gmail.com>
          in_reply_to: automat.marlin.api@gmail.com
          ignore_cert: false
          html_body: file://${{ github.run_number }}-email-summary-ui-test-report.html
          attachments: output/${{ github.run_number }}-summary-test-results.html
        continue-on-error: true
